"use client";

import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { PermissionTable, Step } from "../shared";

export default function JournalSection() {
    return (
        <div className="max-w-3xl mx-auto space-y-10">

            <div>
                <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight mb-4">Overview</h2>
                <p className="leading-7 mb-4">
                    Journal Entries provide a mechanism for recording manual accounting transactions that are
                    not automatically generated by the system. These entries follow double-entry bookkeeping
                    principles, where total debits must equal total credits.
                </p>
                <p className="leading-7 mb-6">
                    Common use cases include period-end adjustments, depreciation entries, accruals, prepayments,
                    and correction of errors. All journal entries require managerial or administrative approval
                    before posting to the general ledger.
                </p>

                <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight mb-4 mt-8">Entry States</h2>
                <div className="space-y-3 mb-6">
                    <div className="flex items-start gap-3">
                        <Badge variant="warning" appearance="outline">Draft</Badge>
                        <p className="text-sm leading-relaxed">
                            Entry is being prepared. Can be edited or deleted. Not posted to the ledger.
                        </p>
                    </div>
                    <div className="flex items-start gap-3">
                        <Badge variant="success" appearance="outline">Posted</Badge>
                        <p className="text-sm leading-relaxed">
                            Entry is finalized and recorded in the general ledger. Cannot be edited. Affects
                            financial statements.
                        </p>
                    </div>
                    <div className="flex items-start gap-3">
                        <Badge variant="destructive" appearance="outline">Voided</Badge>
                        <p className="text-sm leading-relaxed">
                            Entry has been reversed. A reversing entry is automatically created to nullify the
                            original transaction.
                        </p>
                    </div>
                </div>

                <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight mb-6 mt-10">Creating a Journal Entry</h2>
                <div className="ml-2">
                    <Step title="Navigate to Journal">
                        Access <strong>Accounting &gt; Journal</strong> from the main menu.
                    </Step>
                    <Step title="Initiate Entry">
                        Click <strong>New Entry</strong>. Specify Entry Date and optional Reference Number.
                    </Step>
                    <Step title="Add Debit Lines">
                        Add one or more debit lines. Select the account from the Chart of Accounts and enter
                        the debit amount. Provide a description for each line.
                    </Step>
                    <Step title="Add Credit Lines">
                        Add corresponding credit lines. The system displays a running balance to ensure debits
                        equal credits.
                    </Step>
                    <Step title="Verify Balance">
                        Confirm that total debits equal total credits. The <strong>Post</strong> button will
                        only activate when the entry is balanced.
                    </Step>
                    <Step title="Post Entry">
                        Click <strong>Post</strong> to commit the transaction to the general ledger. This action
                        is irreversible; corrections require voiding and creating a new entry.
                    </Step>
                </div>

                <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight mt-10 mb-6">Voiding an Entry</h2>
                <div className="ml-2">
                    <Step title="Locate Entry">
                        Find the posted journal entry that requires reversal.
                    </Step>
                    <Step title="Initiate Void">
                        Select <strong>Void</strong> from the action menu. The system will prompt for confirmation.
                    </Step>
                    <Step title="Automatic Reversal">
                        Upon confirmation, the system automatically creates a reversing entry with opposite
                        debit/credit amounts, effectively nullifying the original transaction.
                    </Step>
                </div>

                <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight mt-10 mb-6">Compliance & Audit</h2>
                <p className="leading-7 mb-6">
                    All journal entries are sequentially numbered and immutable once posted. Each entry records
                    the user who created and posted it, along with timestamps. Journal entries are subject to
                    audit review and must include adequate descriptions for each line item.
                </p>

                <PermissionTable
                    resourceName="Journal Entries"
                    userPerms="None (No Access)"
                    managerPerms="View, Create, Update (Draft only), Post, Void"
                    adminPerms="Full Access (including Permanent Delete & Restore)"
                />
            </div>
        </div>
    );
}
